<?php

namespace Smart\Installer\Install;

/**
 * LockFile
 *
 * Writes two markers when installation completes:
 *  - storage/app/installed.lock        (JSON, human-readable, persists across deploys)
 *  - bootstrap/cache/installed.php     (PHP array, hits OPcache, fast boot-time check)
 *
 * Both are checked by InstallerServiceProvider::isInstalled().
 */
class LockFile
{
    public static function write(array $data = []): bool
    {
        $payload = array_merge([
            'installed_at'    => now()->toIso8601String(),
            'php_version'     => PHP_VERSION,
            'laravel_version' => app()->version(),
            'product'         => config('installer.product.name'),
            'product_version' => config('installer.product.version'),
        ], $data);

        $primary   = base_path(config('installer.lock_file.primary', 'storage/app/installed.lock'));
        $secondary = base_path(config('installer.lock_file.secondary', 'bootstrap/cache/installed.php'));

        // Ensure directories exist
        @mkdir(dirname($primary), 0755, true);
        @mkdir(dirname($secondary), 0755, true);

        $jsonOk = (bool) file_put_contents($primary, json_encode($payload, JSON_PRETTY_PRINT));

        $phpContent = "<?php\n\n// Auto-generated by Smart Installer — DO NOT EDIT\nreturn "
                    . var_export($payload, true) . ";\n";
        $phpOk = (bool) file_put_contents($secondary, $phpContent);

        return $jsonOk && $phpOk;
    }

    public static function exists(): bool
    {
        return file_exists(base_path(config('installer.lock_file.primary', 'storage/app/installed.lock')))
            || file_exists(base_path(config('installer.lock_file.secondary', 'bootstrap/cache/installed.php')));
    }

    public static function read(): array
    {
        $primary = base_path(config('installer.lock_file.primary', 'storage/app/installed.lock'));

        if (file_exists($primary)) {
            $data = json_decode(file_get_contents($primary), true);
            if (is_array($data)) {
                return $data;
            }
        }

        $secondary = base_path(config('installer.lock_file.secondary', 'bootstrap/cache/installed.php'));
        if (file_exists($secondary)) {
            return require $secondary;
        }

        return [];
    }

    public static function delete(): void
    {
        $primary   = base_path(config('installer.lock_file.primary', 'storage/app/installed.lock'));
        $secondary = base_path(config('installer.lock_file.secondary', 'bootstrap/cache/installed.php'));

        if (file_exists($primary))   @unlink($primary);
        if (file_exists($secondary)) @unlink($secondary);
    }
}
